name: "Black Duck Scan"
description: "Black Duck Scanning for GitHub CI/CD Workflows"
author: "James Croall"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  debug:
    description: "Debugging"
  url:
    description: "Black Duck URL"
  token:
    description: "Black Duck API Token"
  trustcert:
    description: "Trust Black Duck server certificate"
  project:
    description: "Project name in the Black Duck server"
  version:
    description: "Project version name in the Black Duck server"
  mode:
    description: "Scanning mode, intelligent or rapid"
    default: "rapid"
  file:
    description: "Location of the related file in the repository"
  output:
    description: "Directory in which to save the rapid scan output"
    default: "blackduck-output"
  fix_pr:
    description: "Generate a Fix PR for each insecure component"
    default: "false"
  comment_on_pr:
    description: "Comment on a pull request"
    default: "false"
  sarif:
    description: "Output file for SARIF"
  incremental_results:
    description: "Incremental analysis"
    default: "false"
  upgrade_major:
    description: "Recommend upgrade guidance to major, not just minor, versions"
    default: "false"
  upgrade_indirect:
    description: "Test & upgrade direct dependencies with vulnerable transitive (indirect) dependencies"
    default: "true"
  detect_opts:
    description: "Passthrough options to Detect, comma delimited, exclude leading hyphens"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - --debug
  - ${{ inputs.debug }}
  - --url
  - ${{ inputs.url }}
  - --token
  - ${{ inputs.token }}
  - --trustcert
  - ${{ inputs.trustcert }}
  - --mode
  - ${{ inputs.mode }}
  - --output
  - ${{ inputs.output }}
  - --project
  - ${{ inputs.project }}
  - --version
  - ${{ inputs.version }}
  - --fix_pr
  - ${{ inputs.fix_pr }}
  - --comment_on_pr
  - ${{ inputs.comment_on_pr }}
  - --sarif
  - ${{ inputs.sarif }}
  - --incremental_results
  - ${{ inputs.incremental_results }}
  - --upgrade_major
  - ${{ inputs.upgrade_major }}
  - --upgrade_indirect
  - ${{ inputs.upgrade_indirect }}
  - --detect_opts
  - ${{ inputs.detect_opts }}
